disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - vertical_whitespace
  - statement_position
  - todo
excluded:
  - "SwiftChinese/EnglishDefinition+CoreDataClass.swift"
  - "SwiftChinese/EnglishDefinition+CoreDataProperties.swift"
  - "SwiftChinese/TranslationEntry+CoreDataClass.swift"
  - "SwiftChinese/TranslationEntry+CoreDataProperties.swift"
